services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: erp-product-coupon
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: erp-product-coupon
      DATABASE_URL: postgresql://user:password@postgres:5432/erp-product-coupon?schema=public
    ports:
      - "8080:8080" # Só API Gateway
    depends_on:
      - postgres

volumes:
  pgdata:
