# rodar com: docker-compose -f docker-compose.dev.yml up

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - erp-product-coupon-db:/var/lib/postgresql/data

volumes:
  erp-product-coupon-db: