# rodar com: docker-compose -f docker-compose.dev.yml up

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKAJS_NO_PARTITIONER_WARNING: 1
      
  postgres-product:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - erp-sales-db:/var/lib/postgresql/data
  postgres-coupon:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB2}
      POSTGRES_USER: ${POSTGRES_USER2}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD2}
    ports:
      - '5433:5432'
    volumes:
      - erp-sales-db2:/var/lib/postgresql/data2

volumes:
  erp-sales-db:
  erp-sales-db2: